global using System.Diagnostics.CodeAnalysis;
global using System.Text;
global using System.Text.Json;
global using Domain.Notifications;
global using Infrastructure.Queue;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Options;
global using RabbitMQ.Client;
global using Serilog;