name: Armut Build & Test

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@main
        with:
          dotnet-version: "7.0.x"

      - name: Restore dependencies
        run: dotnet restore Armut.sln;

      - name: Build
        run: dotnet build Armut.sln -c Release --no-restore;

      - name: Test
        run: dotnet test Armut.sln -c Release --no-build;